name: testgsschoolst
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^7.1.0
  provider: ^5.0.0
  sqflite: ^2.0.0+3

  flutter_page_indicator: ^0.0.3
  dots_indicator: ^2.0.0 
  http: ^0.13.3
  connectivity: ^3.0.3
  flutter_spinkit: ^5.0.0
  decorated_icon: ^1.2.0 
  url_launcher: ^6.0.3
  material_design_icons_flutter: ^4.0.5955
  flutter_swiper_null_safety: ^1.0.0
  carousel_slider: ^3.0.0
  intl: ^0.17.0
  flutter_image_compress: ^1.0.0
  image_picker: ^0.7.5+2
  get_it: ^7.1.3
  fluttertoast: ^8.0.7 
  shared_preferences: ^2.0.5
  rflutter_alert: ^2.0.2
  cupertino_icons: ^0.1.3
  cached_network_image: ^3.0.0
  flutter_countdown_timer: ^4.1.0 
  extended_image: ^4.1.0 
  flutter_cached_pdfview:  
  location: ^4.1.1
  youtube_player_flutter: ^8.0.0
  google_api_availability: ^3.0.1 
  flutter_colorpicker: ^0.3.5
  flutter_iconpicker: 

  video_player: ^2.1.1
  flutter_staggered_grid_view: ^0.4.0
  photo_view: ^0.11.1
  font_awesome_flutter: ^9.0.0
  dio: ^4.0.0 
  path_provider:
  flutter_downloader:
  rotated_corner_decoration: ^2.0.0
  image_editor: ^1.0.0
  device_info: ^0.4.2+4
  icon_picker: ^2.0.0

  share: ^2.0.1
  flutter_native_splash: 
  flutter_launcher_icons: ^0.9.0
  jiffy: ^4.1.0
  flutter_tex: ^4.0.1
  overlay_support: ^1.2.1
dependency_overrides:
  # intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
